server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Compression
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml image/svg+xml;

    # Cache assets statiques
    location = /index.html {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }

    location = /ngsw-worker.js {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }

    location = /ngsw.json {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|webmanifest)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # SPA : toutes les routes vers index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
